name: project_molz
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  google_fonts: ^4.0.4
  http: ^1.1.0
  flutter_screenutil: ^5.8.4
  animation_wrappers: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/svg/
    - assets/png/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf

    - family: Franie
      fonts:
        - asset: assets/fonts/Franie/Franie-Black.ttf
        - asset: assets/fonts/Franie/Franie-BlackItalic.ttf
        - asset: assets/fonts/Franie/Franie-Bold.ttf
        - asset: assets/fonts/Franie/Franie-BoldItalic.ttf
        - asset: assets/fonts/Franie/Franie-ExtraBold.ttf
        - asset: assets/fonts/Franie/Franie-ExtraBoldItalic.ttf
        - asset: assets/fonts/Franie/Franie-ExtraLight.ttf
        - asset: assets/fonts/Franie/Franie-ExtraLightItalic.ttf
        - asset: assets/fonts/Franie/Franie-Hair.ttf
        - asset: assets/fonts/Franie/Franie-HairItalic.ttf
        - asset: assets/fonts/Franie/Franie-Italic.ttf
        - asset: assets/fonts/Franie/Franie-Light.ttf
        - asset: assets/fonts/Franie/Franie-LightItalic.ttf
        - asset: assets/fonts/Franie/Franie-Regular.ttf
        - asset: assets/fonts/Franie/Franie-SemiBold.ttf
        - asset: assets/fonts/Franie/Franie-SemiBoldItalic.ttf
        - asset: assets/fonts/Franie/Franie-SemiLight.ttf
        - asset: assets/fonts/Franie/Franie-SemiLightItalic.ttf


  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
